name: ci

on: push

env:
  SERVER_SECRET: ${{ secrets.SERVER_SECRET }} 
  SERVER_URI: ${{ secrets.SERVER_URI }} 
  SERVER_EMAIL: ${{ secrets.SERVER_EMAIL }} 
  PLATFORM_URI: ${{ secrets.PLATFORM_URI }} 
  MONGODB_URI: ${{ secrets.MONGODB_URI }} 

jobs:
  ci:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependences 
        run: npm install
      - name: Run test
        run: npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pwd
            cd ~/se2/12/
            git pull https://${{ secrets.CLONE_TOKEN }}@github.com/SoftwareEngineering2-Assignment/se2-backend-group12
            cd se2-backend
            git reset --hard origin/main
            npm install
            pm2 restart se2-backend-12 --update-env
